const draftTemplates = [
  {
    id: "agreement-to-sale",
    title: "Agreement to Sale",
    description: "Pre-sale agreement outlining terms before final sale.",
    prompt: "Draft an Agreement to Sale between the seller and the buyer. Include property/asset description, sale consideration, payment schedule, conditions precedent to completion, representations and warranties, indemnities, and timelines for completion of sale.",
  },
  {
    id: "api-integration",
    title: "API Integration Agreement",
    description: "Terms for integrating and using APIs between parties.",
    prompt: "Draft an API Integration Agreement between the API provider and the integrating party. Include scope of API access, usage limits and rate restrictions, authentication and security requirements, data handling obligations, uptime SLA, support terms, intellectual property rights, liability limitations, and termination provisions.",
  },
  {
    id: "asset-purchase",
    title: "Asset Purchase Agreement",
    description: "Agreement for purchase of assets between buyer and seller.",
    prompt: "Draft an Asset Purchase Agreement between the buyer and the seller. Include description of assets being purchased, purchase price and payment terms, representations and warranties from both parties, conditions to closing, indemnification provisions, non-compete covenants, and transition obligations.",
  },
  {
    id: "co-founders",
    title: "Co-founders Agreement",
    description: "Defines roles, equity, and governance between co-founders.",
    prompt: "Draft a Co-founders Agreement for a startup. Include equity split and vesting schedule, roles and responsibilities of each co-founder, decision-making and voting rights, intellectual property assignment, non-compete and non-solicitation clauses, exit and transfer provisions, dispute resolution mechanism, and founder departure scenarios.",
  },
  {
    id: "commercial-lease",
    title: "Commercial Lease Agreement",
    description: "Lease terms for commercial property between parties.",
    prompt: "Draft a Commercial Lease Agreement between the landlord and the tenant. Include premises description, lease term and renewal options, rent amount and escalation, security deposit, permitted use, maintenance and repair obligations, insurance requirements, subletting provisions, default and remedies, and termination clauses.",
  },
  {
    id: "consultancy-services",
    title: "Consultancy Services Agreement",
    description: "Terms for consultancy services between consultant and client.",
    prompt: "Draft a Consultancy Services Agreement between the consultant and the client. Include scope of services, deliverables and milestones, fees and payment terms, term and termination, confidentiality obligations, intellectual property ownership, non-solicitation, liability and indemnification, and dispute resolution.",
  },
  {
    id: "content-license",
    title: "Content Licensee Agreement",
    description: "License terms for use of content by licensee.",
    prompt: "Draft a Content License Agreement between the licensor and the licensee. Include description of licensed content, scope of license (exclusive/non-exclusive), permitted uses and restrictions, territory and duration, royalty or license fee structure, attribution requirements, content modification rights, warranties and representations, termination, and reversion of rights.",
  },
  {
    id: "distributorship",
    title: "Distributorship Agreement",
    description: "Distribution rights and obligations for supplier and distributor.",
    prompt: "Draft a Distributorship Agreement between the supplier/manufacturer and the distributor. Include territory and exclusivity, products covered, pricing and payment terms, minimum purchase obligations, marketing and promotion responsibilities, trademark usage, quality standards, reporting obligations, term and termination, and post-termination obligations.",
  },
  {
    id: "event-management",
    title: "Event Management Agreement",
    description: "Engagement terms for event management services.",
    prompt: "Draft an Event Management Agreement between the client and the event management company. Include event description and scope of services, budget and payment schedule, venue and vendor coordination responsibilities, timeline and milestones, cancellation and postponement terms, force majeure, insurance and liability, intellectual property in event materials, and confidentiality.",
  },
  {
    id: "franchise",
    title: "Franchise Agreement",
    description: "Terms for franchising relationship between parties.",
    prompt: "Draft a Franchise Agreement between the franchisor and the franchisee. Include franchise grant and territory, franchise fees and royalties, training and support obligations, brand standards and quality control, advertising contributions, supply chain requirements, term and renewal, transfer restrictions, termination and post-termination obligations, and non-compete provisions.",
  },
  {
    id: "leave-license",
    title: "Leave and License Agreement",
    description: "License terms for temporary use of property.",
    prompt: "Draft a Leave and License Agreement between the licensor (property owner) and the licensee. Include property description, license period, monthly license fee, security deposit, maintenance responsibilities, permitted use, restrictions, termination notice period, and conditions for renewal.",
  },
  {
    id: "llp",
    title: "LLP Agreement",
    description: "Partnership terms for a limited liability partnership.",
    prompt: "Draft a Limited Liability Partnership (LLP) Agreement. Include name and business of LLP, capital contribution of each partner, profit and loss sharing ratio, rights and duties of designated partners, decision-making process, admission and retirement of partners, accounts and audit provisions, dissolution provisions, and dispute resolution.",
  },
  {
    id: "loi-term-sheet",
    title: "LOI Term Sheet Agreement",
    description: "Letter of intent outlining key deal terms.",
    prompt: "Draft a Letter of Intent / Term Sheet for a proposed transaction. Include description of the proposed deal, key commercial terms, valuation and pricing, due diligence process, exclusivity period, conditions precedent, timeline for definitive agreement, binding vs non-binding provisions, confidentiality, and break-up fees if applicable.",
  },
  {
    id: "management-services",
    title: "Management Services Agreement",
    description: "Terms for management services by provider to client.",
    prompt: "Draft a Management Services Agreement between the service provider and the client. Include scope of management services, performance standards and KPIs, fees and payment terms, reporting obligations, personnel and staffing, confidentiality, intellectual property, liability and indemnification, term and termination, and transition assistance.",
  },
  {
    id: "marketing-advertising",
    title: "Marketing & Advertising Services Agreement",
    description: "Service terms for marketing and advertising engagements.",
    prompt: "Draft a Marketing and Advertising Services Agreement between the agency and the client. Include scope of services and deliverables, campaign objectives, budget and fee structure, approval process, intellectual property and creative ownership, brand guidelines compliance, performance metrics and reporting, confidentiality, term and termination, and liability provisions.",
  },
  {
    id: "mou",
    title: "Memorandum of Understanding",
    description: "Non-binding understanding of intent between parties.",
    prompt: "Draft a Memorandum of Understanding (MoU) between the parties. Include purpose and objectives, roles and responsibilities of each party, scope of collaboration, resource commitments, duration, confidentiality provisions, non-binding nature clause, dispute resolution, amendment process, and termination provisions.",
  },
  {
    id: "music-license",
    title: "Music Licensee Agreement",
    description: "License terms for use of music by licensee.",
    prompt: "Draft a Music License Agreement between the licensor (rights holder) and the licensee. Include description of musical works, type of license (sync, master, mechanical), permitted uses and platforms, territory and duration, royalty structure or flat fee, attribution and credit requirements, modification restrictions, sub-licensing rights, warranties, and termination.",
  },
  {
    id: "nda",
    title: "Non-Disclosure Agreement",
    description: "Confidentiality terms between disclosing and receiving parties.",
    prompt: "Draft a Non-Disclosure Agreement (NDA) between the disclosing party and the receiving party. Include definition of confidential information, obligations of receiving party, exclusions from confidentiality, permitted disclosures, term and survival period, return or destruction of information, remedies for breach, and governing law.",
  },
  {
    id: "partnership",
    title: "Partnership Agreement",
    description: "Partnership terms between partners.",
    prompt: "Draft a Partnership Agreement between the partners. Include name and purpose of partnership, capital contributions, profit and loss sharing, management and decision-making authority, admission of new partners, withdrawal and retirement, non-compete restrictions, dissolution terms, accounts and auditing, and dispute resolution.",
  },
  {
    id: "power-of-attorney",
    title: "Power of Attorney",
    description: "Authorizes an agent to act on behalf of a principal.",
    prompt: "Draft a Power of Attorney document. Include principal and agent details, scope of authority granted (general or specific), effective date and duration, conditions for revocation, compensation (if any), agent's duties and fiduciary obligations, third-party reliance provisions, governing law, and execution requirements.",
  },
  {
    id: "sale-agreement",
    title: "Sale Agreement",
    description: "Agreement for sale of goods or assets between parties.",
    prompt: "Draft a Sale Agreement between the seller and the buyer. Include detailed description of goods/assets, purchase price and payment terms, delivery terms and timeline, inspection and acceptance, risk of loss transfer, warranties and representations, indemnification, limitation of liability, and governing law.",
  },
  {
    id: "shareholders",
    title: "Shareholders Agreement",
    description: "Rights and obligations among shareholders.",
    prompt: "Draft a Shareholders Agreement among the shareholders of the company. Include share capital structure, board composition and voting, reserved matters, dividend policy, transfer restrictions (ROFR, tag-along, drag-along), anti-dilution provisions, information rights, non-compete obligations, deadlock resolution, and exit mechanisms.",
  },
  {
    id: "share-purchase",
    title: "Share Purchase Agreement",
    description: "Terms for share purchase between buyer and seller.",
    prompt: "Draft a Share Purchase Agreement between the seller and the buyer. Include shares being sold, purchase price and payment mechanism, conditions precedent, representations and warranties, indemnification, non-compete and non-solicitation, pre-completion covenants, completion mechanics, post-completion adjustments, and governing law.",
  },
  {
    id: "share-subscription",
    title: "Share Subscription Agreement",
    description: "Terms for investor subscription to company shares.",
    prompt: "Draft a Share Subscription Agreement between the company and the investor. Include number and class of shares, subscription price, conditions precedent, representations and warranties from both parties, use of proceeds, board observer or seat rights, anti-dilution protection, information rights, lock-in period, and exit provisions.",
  },
  {
    id: "sponsorship",
    title: "Sponsorship Agreement",
    description: "Terms between sponsor and sponsored party for support.",
    prompt: "Draft a Sponsorship Agreement between the sponsor and the sponsored party. Include sponsorship benefits and entitlements, sponsorship fee and payment schedule, branding and logo placement, exclusivity provisions, event or activity details, performance obligations, intellectual property usage, reporting and accountability, term and renewal, and termination.",
  },
  {
    id: "staffing-services",
    title: "Staffing Services Agreement",
    description: "Terms for staffing services between agency and client.",
    prompt: "Draft a Staffing Services Agreement between the staffing agency and the client. Include scope of staffing services, candidate sourcing and screening process, fee structure and payment terms, replacement and refund policy, client obligations, non-solicitation of placed candidates, confidentiality, liability and indemnification, term and termination, and governing law.",
  },
  {
    id: "trademark-assignment",
    title: "Trademark Assignment Agreement",
    description: "Assignment of trademark rights from assignor to assignee.",
    prompt: "Draft a Trademark Assignment Agreement between the assignor and the assignee. Include trademark details (registration number, class, goods/services), consideration, assignment scope (with or without goodwill), representations and warranties of assignor, recordal obligations, indemnification, further assurances, and governing law.",
  },
  {
    id: "work-for-hire",
    title: "Work for Hire Agreement",
    description: "Defines ownership and terms for commissioned work.",
    prompt: "Draft a Work for Hire Agreement between the client/commissioner and the creator/contractor. Include description of work to be created, ownership and IP assignment, compensation and payment schedule, delivery timeline and milestones, revision and approval process, creator's moral rights waiver (if applicable), confidentiality, warranties of originality, and termination provisions.",
  },
];

export default draftTemplates;
